#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=30        \
blur_radius=30   \
position=top     \
sticky=on       \
padding_left=1  \
padding_right=1 \
color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:12.0"  \
icon.color=$WHITE                 \
label.font="SF Pro:Semibold:12.0" \
label.color=$WHITE                \
background.color=$ITEM_BG_COLOR       \
background.corner_radius=100            \
background.height=24                  \
padding_left=1                        \
padding_right=1                       \
label.padding_left=1                  \
label.padding_right=5                \
icon.padding_left=5                 \
icon.padding_right=5

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/space_windows.sh

# -- Right Side Of Notch Items --

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/media.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update

# Stop the watcher created by the previous config load.
pkill -f "$CONFIG_DIR/helpers/media_watcher.sh" 2>/dev/null

# sketchybarrc is executed by SketchyBar, so $PPID is its PID.
SKETCHYBAR_PID="$PPID" \
  "$CONFIG_DIR/helpers/media_watcher.sh" \
  >>/tmp/sketchybar_media.log \
  2>>/tmp/sketchybar_media.err &
